/*
 * Copyright (c) 2017 Your Name <you@example.com>
 * Copyright (c) 2020 Another Author <author@example.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */   

#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_split_3x5_2(

        KC_Q, KC_W, KC_F, KC_P, KC_B,                                   KC_J, KC_L, KC_U, KC_Y, KC_SCLN,
        LCTL_T(KC_A), LALT_T(KC_R), LGUI_T(KC_S), LSFT_T(KC_T), KC_G,   KC_M, RSFT_T(KC_N), RGUI_T(KC_E), RALT_T(K
C_I), RCTL_T(KC_O),
        KC_Z, KC_X, KC_C, KC_D, KC_V,                                   KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH,
        KC_SPC, TL_LOWR,                                                TL_UPPR, KC_BSPC
        ),


        [1] = LAYOUT_split_3x5_2(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LCTL_T(KC_A), LALT_T(KC_S), LGUI_T(KC_D), LSFT_T(KC_F), KC_G, KC_H, RSFT_T(KC_J), RGUI_T(KC_K), RALT_T(KC_L
), RCTL_T(KC_SCLN), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),


        [2] = LAYOUT_split_3x5_2(KC_TAB, DM_REC1, DM_PLY1, CW_TOGG, KC_NO, KC_BRIU, KC_MUTE, KC_VOLD, KC_VOLU, KC_BSPC, KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, SELWORD, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, K
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

